Repository manan-shxrma/dsalgo, pull requests merged in 2022-10, with the labels that each got.

#10 Create wordbreak_2.cpp
  dynamicprogramming/wordbreak_2.cpp
Labels: hacktoberfest-accepted

#11 fibbonacci series added
  dynamicprogramming/fibbonacci.cpp
  dynamicprogramming/fibbonacci.exe
Labels: hacktoberfest-accepted

#13 Add files via upload
  lesson.cpp
  ms.cpp
Labels: hacktoberfest-accepted

#16 created binary search using cpp
  Searching/bsearch.cpp
Labels: hacktoberfest-accepted

#15 Create 1143-longest-common-subsequence
  dynamicprogramming/1143-longest-common-subsequence
Labels: hacktoberfest-accepted

#22 Boruvka's algorithm to find Minimum Spanning
  Searching/Dijkstra.cpp
  Searching/binary.cpp
  Searching/greedyalgo.py
Labels: good first issue, hacktoberfest-accepted

#24 Dijkstra's dia limplementation
  Searching/dialimplementation.cpp
Labels: hacktoberfest-accepted

#25 LinkedList with Swap Nodes Operation
  Abstract Data Types (ADT)/Linked List/LinkedList.cpp
  Abstract Data Types (ADT)/Linked List/SwapForLinkedList.cpp
Labels: hacktoberfest-accepted

#36 N_Qeen.cpp
  backtracking/N_Qeen.cpp
Labels: hacktoberfest-accepted

#42 Find Nearest Point That Has the Same X or Y Coordinate
  Miscellaneous/nearest_coordinate.cpp
Labels: hacktoberfest-accepted

#45 Doubly Linked List Implementation
  Abstract Data Types (ADT)/Linked List/doublyLinkedList.cpp
Labels: hacktoberfest-accepted

#44 Update bubblesort.cpp
  Sorting/bubblesort.cpp
Labels: hacktoberfest-accepted

#48 reverse_a_string.cpp
  dynamicprogramming/reverse_a_string
Labels: hacktoberfest-accepted

#52 Updated the Readme file
  README.md
Labels: hacktoberfest-accepted

#50 Added .gitignore for .exe
  Abstract Data Types (ADT)/Linked List/doublyLinkedList.cpp
  CODE_OF_CONDUCT.md
  Graphs/.gitignore
  Graphs/AdjacencyListNode.exe
  Graphs/AdjacencyListVector.exe
  Graphs/AdjancenyList.exe
  Graphs/BFSearch.exe
  Graphs/BFs shortestPath.exe
  Graphs/DFS.exe
  Graphs/Graph Educative/AdjacencyMatrixToList.exe
  Graphs/Graph Educative/WeightedAdjacencyMatrix.exe
  Graphs/GraphsWithVectors/GraphVector.exe
  Graphs/TopologicalSorting.exe
  Graphs/dijkstra.exe
  LICENSE
  Searching/linearsearch.exe
  Sorting/radixsort.cpp
  backtracking/knightstour.cpp
  backtracking/ratinamaze.cpp
  dynamicprogramming/dividenconquer.cpp
  dynamicprogramming/fibbonacci.exe
Labels: hacktoberfest-accepted

#55 Bubble_Sort in Linked List
  Linked List/Bubblesortinlinkedlist.cpp
Labels: hacktoberfest-accepted

#53 Heap Sort
  Sorting/HeapSort.cpp
Labels: hacktoberfest-accepted

#54 Pattern Searching Algorithms
  Pattern Searching Algorithms/KMP-algorithm.cpp
  Pattern Searching Algorithms/Naive-algorithm.cpp
  Sliding Window/Sliding-window.cpp
Labels: hacktoberfest-accepted

#59 added pattern searching and sub added naive searching
  patternsearching/naivealgo.cpp
Labels: hacktoberfest-accepted

#60 Priority Queue added
  Priority Queue/heap-implementation.cpp
  Priority Queue/inplace-heap-sort.cpp
Labels: hacktoberfest-accepted

#61 Python and C code removed
  hashing/arr_equal_or_not.py
  hashing/most_frequent.py
Labels: hacktoberfest-accepted

#64 3 files deleted
  Searching/Dijkstra.cpp
  Searching/dialimplementation.cpp
  Searching/interpolation.cpp
Labels: hacktoberfest-accepted

#65 Lambda Functions
  Lambda Functions/.vscode/c_cpp_properties.json
  Lambda Functions/Capturelistbyvalue.png
  Lambda Functions/Literals and constants/errors.png
  Lambda Functions/Literals and constants/literals.png
  Lambda Functions/Literals and constants/moreliterals.png
  Lambda Functions/Literals and constants/stringliterals.png
  Lambda Functions/capallbyvalue.png
  Lambda Functions/captreallbyreferance.png
  Lambda Functions/capturelist.cpp
  Lambda Functions/capturelistbyreference.png
  Lambda Functions/compiletime.png
  Lambda Functions/constant expressions/Screenshot 2021-10-23 122424.png
  Lambda Functions/constantexpressions.png
  Lambda Functions/lambda.cpp
  Lambda Functions/tempCodeRunnerFile.cpp
Labels: hacktoberfest-accepted

#66 Create Create graphfunctions.cpp
  Create graphfunctions.cpp
Labels: hacktoberfest-accepted

#67 Create Rotate bits of a number
  dynamicprogramming/Rotate bits of a number
Labels: hacktoberfest-accepted

#68 dp/Edit Distance
  dynamicprogramming/Edit Distance.cpp
Labels: hacktoberfest-accepted

#74 Stack Implementation
  Stack/stackArray.cpp
  Stack/stackLinkedList.cpp
Labels: hacktoberfest-accepted

#73 Added Leetcode famous k-frequent
  Priority Queue/k-frequent.cpp
Labels: hacktoberfest-accepted

#75 Added Leetcode k closest origin
  Priority Queue/k-closest-origin.cpp
Labels: hacktoberfest-accepted

#79 Added Leetcode problem rainwater trapping
  Stack/rainwater-trapping.cpp
Labels: hacktoberfest-accepted

#84 Queue implementation
  Queue/queueArray.cpp
  Queue/queueLinkedList.cpp
Labels: hacktoberfest-accepted

#82 Added GFG Problem Activity Selection
  Greedy/activity-selection.cpp
Labels: hacktoberfest-accepted

#87 Quick sort.cpp
  Sorting/Quick sort.cpp
Labels: hacktoberfest-accepted

#86 Update stackLinkedList.cpp
  Stack/stackLinkedList.cpp
Labels: hacktoberfest-accepted

#92 Added balanced parenthesis
  Stack/balancedparenthesis.cpp
Labels: hacktoberfest-accepted

#95 OOPS ADDED
  OOPS/Inheritance/inheritance.cpp
  OOPS/Inheritance/input.txt
  OOPS/Inheritance/output.txt
Labels: hacktoberfest-accepted

#94 Added "Next Greater Element"
  Stack/nextgreaterelement.cpp
Labels: hacktoberfest-accepted

#98 Top View of Binary Tree Added
  Tree/topView.cpp
Labels: hacktoberfest-accepted

#96 Backtracking Concept and Code
  backtracking/Leetcode/n_queens_leetcode.cpp
  backtracking/backtracking_array.cpp
  backtracking/backtracking_vector.cpp
  backtracking/findsubsets.cpp
  backtracking/generatingBrackets.cpp
  backtracking/gridWays.cpp
  backtracking/input.txt
  backtracking/n_queens.cpp
  backtracking/output.txt
  backtracking/permutations.cpp
  backtracking/permutations_number.cpp
  backtracking/sudoku.cpp
Labels: hacktoberfest-accepted

#90 Create CoinChange.cpp
  dynamicprogramming/CoinChange.cpp
Labels: hacktoberfest-accepted

#99 Added code for preorder bst
  Tree/BST creation from given Preorder traversal in c++.cpp
Labels: hacktoberfest-accepted

#116 Updated the contribution.md file
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#117 Create 2 stack is an array
  Stack/2StackInAnArray.cpp
Labels: hacktoberfest-accepted

#115 Create Counting-Sort.cpp
  Sorting/Counting-Sort.cpp
Labels: hacktoberfest-accepted

#114 Create Remove_Nth_Node_From_End_of_List.cpp
  Linked List/Remove_Nth_Node_From_End_of_List.cpp
Labels: hacktoberfest-accepted

#118 create Level_order_traversal_in_Binary_Tree.cpp
  Tree/Level_order_traversal_in_Binary_Tree.cpp
Labels: hacktoberfest-accepted

#123 Create Tarjan_Algorithm.cpp
  Graphs/Tarjan_Algorithm.cpp
Labels: hacktoberfest-accepted

#124 Create cycle-sort.cpp
  Sorting/cycle-sort.cpp
Labels: hacktoberfest-accepted

#131 Create PrintSubSequence.cpp
  Miscellaneous/PrintSubSequence.cpp
Labels: hacktoberfest-accepted

#134 Create BitwiseXOR.cpp
  dynamicprogramming/BitwiseXOR.cpp
Labels: hacktoberfest-accepted

#138 Uploaded insertion sort
  Sorting/DNF sort.cpp
  Sorting/insertion sort.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#137 Create Contains-Duplicate-II.cpp
  Sliding Window/Contains-Duplicate-II.cpp
Labels: hacktoberfest-accepted

#135 Create Tower Of Hanoi.cpp
  Recursion/Tower Of Hanoi.cpp
Labels: hacktoberfest-accepted

#140 DNF sort
  DNF sort.cpp
Labels: hacktoberfest-accepted

#142 Maximum subarray sum
  Miscellaneous/Maximum subarray sum(Kadane's algo).cpp
Labels: hacktoberfest-accepted

#143 Spiral order traversal
  Miscellaneous/Spiral order traversal.cpp
Labels: hacktoberfest-accepted

#148 bitonic sort
  Sorting/bitonicsort.cpp
Labels: hacktoberfest-accepted

#145 Tree/Two Sum IV - Input is a BST
  Tree/653. Two Sum IV - Input is a BST.cpp
  dynamicprogramming/1155. Number of Dice Rolls With Target Sum.cpp
Labels: hacktoberfest-accepted

#149 Create Shell_sort.cpp
  Sorting/Shell_sort.cpp
Labels: hacktoberfest-accepted

#150 Added Ternary Search in Searching
  Searching/TernarySearch.cpp
Labels: hacktoberfest-accepted

#155 Create InfixToPrefix.cpp
  Stack/InfixToPrefix.cpp
Labels: incomplete

#164 Check if There is Loop in list
  Linked List/checkForLoop.cpp
Labels: hacktoberfest-accepted

#188 added stoogesort
  Sorting/stoogesort.cpp
Labels: hacktoberfest-accepted

#182 knapsack.cpp
  Greedy/knapsack.cpp
Labels: hacktoberfest-accepted

#175 Sieve of Eratosthenes
  Miscellaneous/Sieve-of-Eratosthenes
Labels: hacktoberfest-accepted

#176 Pascal's-Triangle.cpp
  Miscellaneous/Pascal's-Triangle
Labels: hacktoberfest-accepted

#177 Zig-Zag-Traversal.cpp
  Binary Tree/Zig-Zag-Traversal
Labels: hacktoberfest-accepted

#178 Bubble_sort.cpp
  Sorting/Bubble_sort.cpp
Labels: spam

#190 prim's_algo.cpp
  Greedy/prim's_algo.cpp
Labels: incomplete

#184 coin_problem.cpp
  Greedy/coin_problem.cpp
Labels: hacktoberfest-accepted

#195 M coloring algorithm
  M-coloring-alogithm/Backtracking-5.cpp
  Sudoku Solving Algorithm/Backtracking7.cpp
  Sudoku Solving Algorithms/Backtracking7.cpp
Labels: hacktoberfest-accepted

#197 Fibonacci using DP
  Fibonacci using DP/nth-fibonacci-number.cpp
  Hamiltonian Cycle/Backtracking-6.cpp
Labels: hacktoberfest-accepted

#200 Create Linked List Cycle II LEETCODE
  Linked List/Linked List Cycle II LEETCODE
Labels: hacktoberfest-accepted

#201 added maximum depth of binary tree
  Binary Tree/Maximum Depth of Binary Tree
Labels: hacktoberfest-accepted

#202 Remove Nth Node From End of List LEETCODE
  Linked List/Remove Nth Node From End of List LEETCODE
Labels: hacktoberfest-accepted

#203 Create Palindrome Linked List
  Linked List/Palindrome Linked List
Labels: hacktoberfest-accepted

#204 Diameter of binary tree
  Binary Tree/Diameter-of-Binary-Tree.cpp
Labels: hacktoberfest-accepted

#206 added Sum Root to Leaf Numbers
  Binary Tree/Sum Root to Leaf Numbers.cpp
Labels: hacktoberfest-accepted

#207 Added Maximum Level Sum of a Binary Tree
  Binary Tree/Maximum Level Sum of a Binary Tree.cpp
Labels: hacktoberfest-accepted

#194 Reverse a string using stacks
  Stack/reverse_string_using_stack.cpp
Labels: incomplete

#212 hufmancode
  Greedy/huffman_code.cpp
Labels: hacktoberfest-accepted

#211 Added the Sublist search program in C++
  Searching/Sublist_search.cpp
Labels: hacktoberfest-accepted

#223 Create longest path in matrix.cpp
  dynamicprogramming/longest path in matrix.cpp
Labels: hacktoberfest-accepted

#221 Create insert after position in a doubly linked list
  Linked List/insert after position in a doubly linked list
Labels: hacktoberfest-accepted

#217 Create Prim’s_Minimum_Spanning_Tree.cpp
  Tree/Prim’s_Minimum_Spanning_Tree.cpp
Labels: hacktoberfest-accepted

#216 Remove_N-th _node_from_the_end_of_a_Linked_List.cpp
  Linked List/Remove_N-th _node_from_the_end_of_a_Linked_List.cpp
Labels: hacktoberfest-accepted

#215 Queue_Using_LinkedList.cpp
  Queue/Queue_Using_LinkedList.cpp
Labels: hacktoberfest-accepted

#226 The puzzle game Magnets involves placing a set of domino-shaped magne…
  backtracking/magnet prob .cpp
Labels: hacktoberfest-accepted

#230 doubly LL palindrone
  DOUBLY_LL_PALINDROME.CPP
Labels: hacktoberfest-accepted

#227 Create Intersection_of_Two_Linked_Lists.cpp
  Linked List/Intersection_of_Two_Linked_Lists.cpp
Labels: hacktoberfest-accepted

#231 Longest Path in a Directed Acyclic Graph code
  Graphs/Longest Path in a Directed Acyclic Graph
  Longest Path in a Directed Acyclic Graph
Labels: hacktoberfest-accepted

#232 wave_sort.cpp
  Sorting/wave_sort.cpp
Labels: hacktoberfest-accepted

#235 inc_dec.cpp
  Recursion/inc_dec.cpp
Labels: hacktoberfest-accepted

#236 Create Box Stacking Problem.cpp
  dynamicprogramming/Box Stacking Problem.cpp
Labels: hacktoberfest-accepted

#240 Remove Duplicates from unsorted Linked List
  Linked List/RemoveDuplicates.cpp
Labels: hacktoberfest-accepted

#241 Clone linkedList with random Pointer
  Linked List/CloneLinkedList.cpp
Labels: hacktoberfest-accepted

#242 Create Number of Island.cpp
  graphs/Number of Island.cpp
Labels: hacktoberfest-accepted

#243 Create boolean paranthesization.cpp
  dynamicprogramming/boolean paranthesization.cpp
Labels: hacktoberfest-accepted

#244 Create Count distinct elements.cpp
  hashing/Count distinct elements.cpp
Labels: hacktoberfest-accepted

#245 Create Word Break Problem.cpp
  dynamicprogramming/Word Break Problem.cpp
Labels: hacktoberfest-accepted

#246 Create Detect cycle in an undirected graph.cpp
  graphs/Detect cycle in an undirected graph.cpp
Labels: hacktoberfest-accepted

#247 Create menu driven all operations linked lists.c
  Linked List/menu driven all operations linked lists.c
Labels: hacktoberfest-accepted

#249 Create checkPrime.cpp
  Miscellaneous/checkPrime.cpp
Labels: hacktoberfest-accepted

#259 Problem solving algo
  deathBlessingalgo.cpp
Labels: hacktoberfest-accepted

#261 Created a page faults in lru chache program
  Greedy/page_faults_in_LRU_Cache.cpp
Labels: hacktoberfest-accepted

#263 Prefix to infix
  Stack/PrefixToInfix.cpp
Labels: hacktoberfest-accepted

#255 sort a linked list of 0s, 1s and 2s
  Linked List/Sort012.cpp
Labels: hacktoberfest-accepted

#254 Create Shortest Prime Path.cpp
  graphs/Shortest Prime Path.cpp
Labels: hacktoberfest-accepted

#273 Create Butterfly Pattern.cpp
  Miscellaneous/Butterfly Pattern.cpp
Labels: hacktoberfest-accepted

#272 Create Circular_list.cpp
  Linked List/Circular_list.cpp
Labels: hacktoberfest-accepted

#274 Create Eggdropping.cpp
  dynamicprogramming/Eggdropping.cpp
Labels: hacktoberfest-accepted

#275 evenOddIncrement cpp
  Miscellaneous/evenOddIncrement.cpp
Labels: hacktoberfest-accepted
